apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: mohamedshawkybayoumi/udagram-api-user:v6
          ports:
            - containerPort: 8080
          env:
            - name: URL
              value: "http://reverseproxy:8080"
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
